### ISSUE TITLE
Redundancia no titulo da página que não é seção

### ISSUE THREAD

**Issue by ppKrauss** [AddressForAll/documentation_generator#2]
Perceptivel por exemplo em http://docs.addressforall.org/WS/address-endpoints/

**Comment by cchness** [comment]
Estou considerando que cada arquivo *.md dentro da docs se refere a uma seção. O exemplo citado ocorre porque a página não possui um titulo (# alguma coisa), então pego o primeiro '## alguma coisa' na página como título da seção.

Devo considerar cada arquivo *.md como referente à uma seção?

**Comment by cchness** [comment]
Considero resolvida essa situação. Agora prepondera a estrutura de títulos utilizada dentro de cada arquivo .md e o tratamento padrão que o mkdocs dá para os títulos.
