### ISSUE TITLE
Migração para mediawiki

### ISSUE THREAD

**Issue by crebollobr** [AddressForAll/documentation_generator#6]
Faze de teste e aprendizagem

- ler manual online
- testar os formatos simples como
- - html
- - tabela
- - código fonte
- - template externo
- - readme.md externo
- - formatação de formulas
- permissão por usuário / editor
- como zerar a wiki 
- imagens e pasta de arquivos
- Teste de backup / recuperação
-

**Comment by ppKrauss** [comment]
Ok, a missão é esta mesma.  Organizando em 3 grandes blocos:

1. Testes com instalação, backup e restauro:
   1.1. instalar, criar conteúdo fake, gerar backup XML (+imagens) e desinstalar; 
   1.2. instalar novamente, restaurar XML 

2. Demais testes antes da instalação definitiva:
   2.2.  import/export de HTML, incluindo tabelas
   2.3. conversão de textos Markdown em Wikitext (pandoc?)
   2.4. Templates da Wikipedia e  Wiki-OSM
   2.5.  Permissão por usuário (apenas quem tem login pode editar)
   2.6. Possibilidade de uso de Mustache com JSON (ex. APIs do OSM.codes) e [HTML_templates](https://www.mediawiki.org/wiki/Manual:HTML_templates).
   2.7. ...

3. Configuração final cuidadosa:
   3.1. Opções de edição Wikitext e WYSIWYG. [ok - já testamos]
   3.2. Subdomínio `wiki` no NGINX. `wiki.adddressforall.org`  como principal, `wiki.osm.codes` redirecionando para ele.
   3.3. [ShortURL](https://www.mediawiki.org/wiki/Manual:Short_URL) com NGINX.
   3.4. Imagens, uploads, etc. em pastas adequadas, sem conflito com shortURL.
   3.5. Instalação de processador de template moderno (ver [Manual:Parser_functions](https://www.mediawiki.org/wiki/Manual:Parser_functions) uso corrente de [Lua](https://en.wikipedia.org/wiki/Help:Lua_for_beginners) na Wikipedia)

**Comment by crebollobr** [comment]
já estamos com wiki em produção, se precisar de algo a mais abrir uma issue especifica
